(* this picks out the shit we care about! *)

document     ::= html_comment? #'\s+'? section section

html_comment ::= #'<!--.*?-->'
word         ::= #'[\p{ASCII}&&[\p{Alnum}\p{Punct}]]+'

header       ::= '=' (header | header_text ) '='
header_text  ::= #'\s+' claim #'\s+'
claim        ::= #'[Dd]efinition' | #'[Pp]roof' | #'[Tt]heorem'


section = header #'[\p{Space}]'? section_content+ ( &header | #'\z')
section_content = #'[\s\p{Print}]'+
