(* this picks out the shit we care about! *)

document     ::= html_comment? #'\s+'? section+

html_comment ::= #'(?s)<!--.*?-->'
word         ::= #'[\p{ASCII}&&[\p{Alnum}\p{Punct}]]+'

header       ::= '=' (header | header_text ) '='
header_text  ::= #'\s+' claim #'\s+'
claim        ::= #'[Dd]efinition' | #'[Pp]roof' | #'[Tt]heorem'


section         ::= header #'[\p{Space}]'* section_content <whitespace>* ( (&header) | #'\z')
(* section_content ::= (inlink / (<whitespace> | content_char))* *)
section_content ::= (inlink / #'[\p{Print}\s]*')*
inlink          ::= #'(?s)\[\[.*?]]'
<content_char>  ::= #'[\p{Print}\v]'
whitespace      ::= #'\s+'

reserved        ::= '[[' | '==='
